config/routes.rb
Rails.application.routes.draw do

  resources :pages

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(pages_params)
      redirect_to pages_path
    else
      render :edit
    end
  end

  def create
    @page = Page.new(pages_params)

    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  private

  def pages_params
    params.require(:page).permit(:title, :author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "pages/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Post it</h1>
<%= form_for @page do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :poster %>
    <%= f.text_field :poster %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit %>
  </div>
    <%= link_to 'Back', pages_path %>
<% end %>

app/views/pages/index.html.erb
<h1>Post it's</h1>
  <p><%= link_to 'New Post it', new_page_path %></p>
  <% @pages.each do |page| %>
    <h2><%= page.title %></h2>
    <%= link_to 'Show Post it', page_path(page) %>
    <%= link_to 'Edit Post it', edit_page_path(page) %>
    <%= link_to 'Destroy Post it', page, method: :delete %>
  <% end %>

app/views/pages/new.html.erb
<h1>New Post it</h1>
<%= form_for @page do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :poster %>
  <%= f.text_field :poster %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div>
  <%= f.submit %>
</div>
  <%= link_to 'Back', pages_path %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<h4><%= @page.poster %></h1>
<p><%= @page.body %></p>
<%= link_to 'Back', pages_path %>